// template/react/src/App.jsx
import React from 'react';
import * as echarts from 'echarts';
import Counter from 'src/components/Counter.jsx';

console.log(echarts);

const homeStyle = {
  maxWidth: 600,
  margin: '10px auto',
  textAlign: 'center'
};

const App = () => {
  return (
    <div style={homeStyle}>
      <h2>Welcome to React - Script Custom Module</h2>
      <p>If you like this project, click "Like" below!!</p>
      <Counter />
    </div>
  );
};

export default App;

// template/vue/src/App.vue
<template>
  <div class="home">
    <h2>Welcome to Vue - Script Custom Module</h2>
    <p>If you like this project, click "Like" below!!</p>
    <Counter />
  </div>
</template>

<script setup>
import * as echarts from 'echarts';
import Counter from 'src/components/Counter.vue';

console.log(echarts);
</script>

<script>
export default {
  name: 'App'
};
</script>

<style lang="scss">
.home {
  max-width: 600px;
  margin: auto;
  text-align: center;
}
</style>
